/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Empresa;

/**
 *
 * @author German
 */
public class JFrameLiquidacionSeguridadSocial extends javax.swing.JFrame {

    /**
     * Creates new form JFrameLiquidacionSeguridadSocial
     */
    public JFrameLiquidacionSeguridadSocial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSeguridadSocial = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPrestacionesSociales = new javax.swing.JTextArea();
        jButtonLiquidarSeguridad = new javax.swing.JButton();
        jButtonLiquidarPrestaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valores de los empleados por concepto de seguridad social");

        jTextAreaSeguridadSocial.setColumns(20);
        jTextAreaSeguridadSocial.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSeguridadSocial);

        jLabel2.setText("Valores de los empleados por concepto de prestaciones sociales");

        jTextAreaPrestacionesSociales.setColumns(20);
        jTextAreaPrestacionesSociales.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPrestacionesSociales);

        jButtonLiquidarSeguridad.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLiquidarSeguridad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLiquidarSeguridad.setText("Liquidar Seguridad Social");
        jButtonLiquidarSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiquidarSeguridadActionPerformed(evt);
            }
        });

        jButtonLiquidarPrestaciones.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLiquidarPrestaciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLiquidarPrestaciones.setText("Liquidar Prestaciones Sociales");
        jButtonLiquidarPrestaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiquidarPrestacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonLiquidarSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(jButtonLiquidarPrestaciones)))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonLiquidarSeguridad)))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButtonLiquidarPrestaciones)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLiquidarSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiquidarSeguridadActionPerformed
        // TODO add your handling code here:
        JFrameEmpleado ventana = new JFrameEmpleado();
        
        for(int x =0; x< ventana.datos.size(); x++){
             //jTextArea1
             System.out.print(Empresa.liquidarSegSocialEmp(ventana.datos).get(x));
             jTextAreaSeguridadSocial.append(Empresa.liquidarSegSocialEmp(ventana.datos).get(x).toString()+"\n");
           
        }
    }//GEN-LAST:event_jButtonLiquidarSeguridadActionPerformed

    private void jButtonLiquidarPrestacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiquidarPrestacionesActionPerformed
        // TODO add your handling code here:
        
                JFrameEmpleado ventana = new JFrameEmpleado();
        
        for(int x =0; x< ventana.datos.size(); x++){
             //jTextArea1
             System.out.print(Empresa.liquidarPrestacionesEmp(ventana.datos).get(x));
             jTextAreaPrestacionesSociales.append(Empresa.liquidarPrestacionesEmp(ventana.datos).get(x).toString()+"\n");
           
        }
        
    }//GEN-LAST:event_jButtonLiquidarPrestacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLiquidacionSeguridadSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLiquidacionSeguridadSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLiquidacionSeguridadSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLiquidacionSeguridadSocial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLiquidacionSeguridadSocial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLiquidarPrestaciones;
    private javax.swing.JButton jButtonLiquidarSeguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaPrestacionesSociales;
    private javax.swing.JTextArea jTextAreaSeguridadSocial;
    // End of variables declaration//GEN-END:variables
}
