/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Empleado;
import Model.Empresa;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author German
 */
public class JFrameEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEmpleado
     */
    public JFrameEmpleado() {
        initComponents();
    }
    
    public static ArrayList<Empleado> datos = new ArrayList();
    public static String texto = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldhorasextra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldsalario = new javax.swing.JTextField();
        jButtoncontratar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonliquidarnomina = new javax.swing.JButton();
        jButtonliquidarseguridad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Contratar Empleado");

        jLabel2.setText("Nombre");

        jTextFieldnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Horas Extra");

        jTextFieldhorasextra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldhorasextraActionPerformed(evt);
            }
        });

        jLabel4.setText("Auxilio trasporte");

        jLabel5.setText("Salario");

        jTextFieldsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsalarioActionPerformed(evt);
            }
        });

        jButtoncontratar.setBackground(new java.awt.Color(0, 0, 0));
        jButtoncontratar.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncontratar.setText("Contratar");
        jButtoncontratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncontratarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButtoncontratar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldnombre)
                            .addComponent(jTextFieldhorasextra)
                            .addComponent(jTextFieldsalario)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldhorasextra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtoncontratar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButtonliquidarnomina.setBackground(new java.awt.Color(0, 0, 0));
        jButtonliquidarnomina.setForeground(new java.awt.Color(255, 255, 255));
        jButtonliquidarnomina.setText("Liquidacion Nomina y Parafiscales\n");
        jButtonliquidarnomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonliquidarnominaActionPerformed(evt);
            }
        });

        jButtonliquidarseguridad.setBackground(new java.awt.Color(0, 0, 0));
        jButtonliquidarseguridad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonliquidarseguridad.setText("Liquidacion Seguridad y Prestaciones\n");
        jButtonliquidarseguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonliquidarseguridadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonliquidarseguridad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonliquidarnomina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButtonliquidarnomina)
                .addGap(55, 55, 55)
                .addComponent(jButtonliquidarseguridad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnombreActionPerformed

    private void jTextFieldhorasextraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldhorasextraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldhorasextraActionPerformed

    private void jTextFieldsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsalarioActionPerformed

    private void jButtoncontratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncontratarActionPerformed
     // TODO add your handling code here:
     
     //ArrayList<Empleado> datos = new ArrayList();
     String nombre, valor_combo;
     int horasExtra;
     boolean auxilioTrasporte;
     int salario;
     nombre =  jTextFieldnombre.getText();
     horasExtra = Integer.parseInt(jTextFieldhorasextra.getText());
    
     if(jComboBox1.getSelectedItem()== "SI"){
        auxilioTrasporte =true;
    }
     else {
          auxilioTrasporte =false; 
     }
     salario = Integer.parseInt(jTextFieldsalario.getText());
     datos.add(new Empleado(nombre,horasExtra,auxilioTrasporte,salario));
     texto = "luisa";
     System.out.print(auxilioTrasporte);
     //System.out.print(datos.get(1));
     //datos.add(new Empleado(nombre,horasExtra,auxilioTrasporte,salario));
     //System.out.print(datos.get(0).getNombre());
     JOptionPane.showMessageDialog(null, "El Empleado ha sido actualizado exitosamente", "Actualizacion exitosa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtoncontratarActionPerformed

    private void jButtonliquidarnominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonliquidarnominaActionPerformed
        // TODO add your handling code here:
        JFrameLiquidacionNomina ventana = new JFrameLiquidacionNomina();
        ventana.setVisible(true);
        this.setVisible(false);
          
    }//GEN-LAST:event_jButtonliquidarnominaActionPerformed

    private void jButtonliquidarseguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonliquidarseguridadActionPerformed
        // TODO add your handling code here:
        JFrameLiquidacionSeguridadSocial ventana = new JFrameLiquidacionSeguridadSocial();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonliquidarseguridadActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncontratar;
    private javax.swing.JButton jButtonliquidarnomina;
    private javax.swing.JButton jButtonliquidarseguridad;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldhorasextra;
    private javax.swing.JTextField jTextFieldnombre;
    private javax.swing.JTextField jTextFieldsalario;
    // End of variables declaration//GEN-END:variables
}
