/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Empresa;

/**
 *
 * @author German
 */
public class JFrameLiquidacionNomina extends javax.swing.JFrame {

    /**
     * Creates new form JFrameLiquidacionNomina
     */
    public JFrameLiquidacionNomina() {
        initComponents();
 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonliquidarnomina = new javax.swing.JButton();
        jButtonliquidarparafiscales = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreanomina = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaParafiscales = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valores de empleados por concepto de nomina");

        jButtonliquidarnomina.setBackground(new java.awt.Color(0, 0, 0));
        jButtonliquidarnomina.setForeground(new java.awt.Color(255, 255, 255));
        jButtonliquidarnomina.setText("Liquidar Nomina");
        jButtonliquidarnomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonliquidarnominaActionPerformed(evt);
            }
        });

        jButtonliquidarparafiscales.setBackground(new java.awt.Color(0, 0, 0));
        jButtonliquidarparafiscales.setForeground(new java.awt.Color(255, 255, 255));
        jButtonliquidarparafiscales.setText("Liquidar Parafiscales\n");
        jButtonliquidarparafiscales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonliquidarparafiscalesActionPerformed(evt);
            }
        });

        jTextAreanomina.setColumns(20);
        jTextAreanomina.setRows(5);
        jScrollPane1.setViewportView(jTextAreanomina);

        jTextAreaParafiscales.setColumns(20);
        jTextAreaParafiscales.setRows(5);
        jScrollPane2.setViewportView(jTextAreaParafiscales);

        jLabel2.setText("Valores empleados por concepto de parafiscales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonliquidarparafiscales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonliquidarnomina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonliquidarnomina)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonliquidarparafiscales)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonliquidarnominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonliquidarnominaActionPerformed
        // TODO add your handling code here:
        JFrameEmpleado ventana = new JFrameEmpleado();
        System.out.print(ventana.texto);
        System.out.print(ventana.datos.size());
        
        Empresa.liquidarNominaEmp(ventana.datos);
        
        for(int x =0; x< ventana.datos.size(); x++){
             //jTextArea1

             System.out.print(Empresa.liquidarNominaEmp(ventana.datos).get(x));
             jTextAreanomina.append(Empresa.liquidarNominaEmp(ventana.datos).get(x).toString()+"\n");
           
        }
        
        //Empresa.liquidarNominaEmp(empleados);
    }//GEN-LAST:event_jButtonliquidarnominaActionPerformed

    private void jButtonliquidarparafiscalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonliquidarparafiscalesActionPerformed
        // TODO add your handling code here:
        JFrameEmpleado ventana = new JFrameEmpleado();
        
        for(int x =0; x< ventana.datos.size(); x++){
             //jTextArea1
             System.out.print(Empresa.liquidarParafiscales(ventana.datos).get(x));
             jTextAreaParafiscales.append(ventana.datos.get(x).getNombre()+": "+Empresa.liquidarParafiscales(ventana.datos).get(x).toString()+"\n");
           
        }
    }//GEN-LAST:event_jButtonliquidarparafiscalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLiquidacionNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLiquidacionNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLiquidacionNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLiquidacionNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLiquidacionNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonliquidarnomina;
    private javax.swing.JButton jButtonliquidarparafiscales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaParafiscales;
    private javax.swing.JTextArea jTextAreanomina;
    // End of variables declaration//GEN-END:variables
}
